name: Create infraestructure into Databricks

on:
  push:
    branches:
      - main
    paths:
      - 'infra/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.10.5

      - name: Configure Databricks variables
        run: |
          echo "TF_VAR_databricks_host=${{ secrets.DATABRICKS_HOST }}" >> $GITHUB_ENV
          echo "TF_VAR_databricks_host=${{ secrets.DATABRICKS_TOKEN }}" >> $GITHUB_ENV
      
      - name: Terraform Init
        run: |
          cd infra
          terraform init

      - name: Apply Terraform
        run: |
          cd infra
          terraform apply -auto-approve -var-file=$TF_ENV
