name: Deploy Databricks bundle

on:
  push:
    branches:
      - main
      - dev
    paths:
      - 'pipeline_elt/**'
      - '.github/workflows/**'

env:
  DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
  DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Databricks CLI
        run: |
          curl -fsSL https://raw.githubusercontent.com/databricks/setup-cli/main/install.sh | sh
          databricks --version
      
      - name: Authenticate Databricks
        run: |
          cd pipeline_elt
          databricks bundle validate
      
      - name: Deploy to Databricks
        run: |
          cd pipeline_elt
          if [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
            echo "Deploying to production"
            databricks bundle deploy --target prod
          elif [[ "${{ github.ref }}" == "refs/heads/dev" ]]; then
            echo "Deploying to dev"
            databricks bundle deploy --target dev
          fi
