name: Deploy to Databricks

on:
  push:
    branches:
      - main
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.10.5

      - name: Define environment variables based on branch
        run: |
          if [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
            echo "TF_ENV=terraform.prod.tfvars" >> $GITHUB_ENV
          else
            echo "TF_ENV=terraform.dev.tfvars" >> $GITHUB_ENV
          fi

      - name: Configure Databricks variables
        run: |
          echo "DATABRICKS_HOST=${{ secrets.DATABRICKS_HOST }}" >> $GITHUB_ENV
          echo "DATABRICKS_TOKEN=${{ secrets.DATABRICKS_TOKEN }}" >> $GITHUB_ENV

      - name: Init Terraform
        run: terraform init

      - name: Apply Terraform
        run: terraform apply -auto-approve -var-file=$TF_ENV
